name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Check formatting
      run: cargo fmt --check
    - name: Check linting
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
    - name: Codecov
      uses: codecov/codecov-action@v3.1.
      
  coverage:
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined

    steps:
      - uses: actions/checkout@v3
      - name: Generate code coverage
        run: cargo tarpaulin --all-features --timeout 120 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.
        with:
          fail_ci_if_error: true
